package ssm

import (
	"context"
	"fmt"
	"slices"
	"sort"
	"strconv"
	"time"

	"github.com/google/uuid"

	"github.com/blackbirdworks/gopherstack/pkgs/store"
)

func (b *InMemoryBackend) maintenanceWindowsStore(region string) *store.Table[MaintenanceWindow] {
	return getOrCreateTable(b, b.maintenanceWindows, "maintenanceWindows", region, maintenanceWindowKeyFn)
}
func (b *InMemoryBackend) maintenanceWindowTargetsStore(
	region string,
) *store.Table[MaintenanceWindowTarget] {
	return getOrCreateTable(
		b, b.maintenanceWindowTargets, "maintenanceWindowTargets", region, maintenanceWindowTargetKeyFn,
	)
}
func (b *InMemoryBackend) maintenanceWindowTasksStore(
	region string,
) *store.Table[MaintenanceWindowTask] {
	return getOrCreateTable(
		b, b.maintenanceWindowTasks, "maintenanceWindowTasks", region, maintenanceWindowTaskKeyFn,
	)
}

// CancelMaintenanceWindowExecution cancels a maintenance window execution.
func (b *InMemoryBackend) CancelMaintenanceWindowExecution(
	_ context.Context,
	input *CancelMaintenanceWindowExecutionInput,
) (*CancelMaintenanceWindowExecutionOutput, error) {
	if input.WindowExecutionID == "" {
		return nil, fmt.Errorf("%w: WindowExecutionId is required", ErrValidationException)
	}

	return &CancelMaintenanceWindowExecutionOutput{
		WindowExecutionID: input.WindowExecutionID,
	}, nil
}

// CreateMaintenanceWindow creates a new maintenance window.
func (b *InMemoryBackend) CreateMaintenanceWindow(
	ctx context.Context,
	input *CreateMaintenanceWindowInput,
) (*CreateMaintenanceWindowOutput, error) {
	if input.Name == "" {
		return nil, fmt.Errorf("%w: Name is required", ErrValidationException)
	}

	if input.Schedule == "" {
		return nil, fmt.Errorf("%w: Schedule is required", ErrValidationException)
	}

	const (
		minWindowDuration = int32(1)
		maxWindowDuration = int32(24)
	)
	if input.Duration < minWindowDuration || input.Duration > maxWindowDuration {
		return nil, fmt.Errorf(
			"%w: Duration must be between 1 and 24 hours",
			ErrValidationException,
		)
	}
	if input.Cutoff >= input.Duration {
		return nil, fmt.Errorf("%w: Cutoff must be less than Duration", ErrValidationException)
	}

	region := getRegion(ctx)
	b.mu.Lock("CreateMaintenanceWindow")
	defer b.mu.Unlock()

	windowID := windowIDPrefix + uuid.NewString()
	now := UnixTimeFloat(time.Now())

	mw := MaintenanceWindow{
		WindowID:                 windowID,
		Name:                     input.Name,
		Description:              input.Description,
		Schedule:                 input.Schedule,
		ScheduleTimezone:         input.ScheduleTimezone,
		ScheduleOffset:           input.ScheduleOffset,
		StartDate:                input.StartDate,
		EndDate:                  input.EndDate,
		Duration:                 input.Duration,
		Cutoff:                   input.Cutoff,
		AllowUnassociatedTargets: input.AllowUnassociatedTargets,
		Enabled:                  true,
		CreatedDate:              now,
		ModifiedDate:             now,
	}

	b.maintenanceWindowsStore(region).Put(&mw)

	if len(input.Tags) > 0 {
		if b.miscResourceTags[region] == nil {
			b.miscResourceTags[region] = make(map[string]map[string]string)
		}
		miscTags := b.miscResourceTagsStore(region)
		if miscTags[windowID] == nil {
			miscTags[windowID] = make(map[string]string)
		}
		for _, t := range input.Tags {
			miscTags[windowID][t.Key] = t.Value
		}
	}

	return &CreateMaintenanceWindowOutput{WindowID: windowID}, nil
}

const mwExecIDPrefix = "mwexec-"

// mwExecID builds a deterministic execution ID from a window ID.
// mwToIdentity projects a stored MaintenanceWindow onto the narrower
// MaintenanceWindowIdentity listing shape (DescribeMaintenanceWindows,
// DescribeMaintenanceWindowsForTarget).
func mwToIdentity(mw *MaintenanceWindow) MaintenanceWindowIdentity {
	return MaintenanceWindowIdentity{
		WindowID:          mw.WindowID,
		Name:              mw.Name,
		Description:       mw.Description,
		Schedule:          mw.Schedule,
		ScheduleTimezone:  mw.ScheduleTimezone,
		StartDate:         mw.StartDate,
		EndDate:           mw.EndDate,
		NextExecutionTime: mwNextExecutionTime(),
		Duration:          mw.Duration,
		Cutoff:            mw.Cutoff,
		ScheduleOffset:    mw.ScheduleOffset,
		Enabled:           mw.Enabled,
	}
}

func mwExecID(windowID string) string { return mwExecIDPrefix + windowID }

// mwNextExecutionTime returns a synthetic next-run time -- this backend has
// no real cron/rate-expression evaluator to derive a genuine one from
// Schedule, matching the same fixed-offset heuristic
// DescribeMaintenanceWindowSchedule already uses.
func mwNextExecutionTime() string {
	return time.Now().UTC().Add(mwExecutionScheduleHours * time.Hour).Format(time.RFC3339)
}

// mwWindowIDFromExec extracts the window ID from a deterministic execution ID.
// Returns ("", false) if the execution ID was not generated by mwExecID.
func mwWindowIDFromExec(execID string) (string, bool) {
	if len(execID) <= len(mwExecIDPrefix) || execID[:len(mwExecIDPrefix)] != mwExecIDPrefix {
		return "", false
	}

	return execID[len(mwExecIDPrefix):], true
}

// DescribeMaintenanceWindowExecutions returns execution records for a window.
// When the window exists it returns a single synthetic execution record derived
// from the window's state (simulating that the window has run once).
func (b *InMemoryBackend) DescribeMaintenanceWindowExecutions(
	ctx context.Context,
	input *DescribeMaintenanceWindowExecutionsInput,
) (*DescribeMaintenanceWindowExecutionsOutputFull, error) {
	if input.WindowID == "" {
		return nil, fmt.Errorf("%w: WindowId is required", ErrValidationException)
	}

	region := getRegion(ctx)
	b.mu.RLock("DescribeMaintenanceWindowExecutions")
	defer b.mu.RUnlock()

	win, exists := b.maintenanceWindowsStore(region).Get(input.WindowID)
	if !exists {
		return &DescribeMaintenanceWindowExecutionsOutputFull{
			WindowExecutions: []MaintenanceWindowExecution{},
		}, nil
	}

	var execTime time.Time
	if win.CreatedDate > 0 {
		execTime = time.Unix(int64(win.CreatedDate), 0).UTC()
	} else {
		execTime = time.Now().UTC()
	}

	endTime := execTime.Add(time.Duration(win.Duration) * time.Hour)

	return &DescribeMaintenanceWindowExecutionsOutputFull{
		WindowExecutions: []MaintenanceWindowExecution{
			{
				WindowID:          win.WindowID,
				WindowExecutionID: mwExecID(win.WindowID),
				Status:            commandStatusSuccess,
				StartTime:         UnixTimeFloat(execTime),
				EndTime:           UnixTimeFloat(endTime),
			},
		},
	}, nil
}

// DescribeMaintenanceWindowExecutionTasks returns task executions for a window execution.
// Derives the window ID from the execution ID and looks up registered tasks for that window.
func (b *InMemoryBackend) DescribeMaintenanceWindowExecutionTasks(
	ctx context.Context,
	input *DescribeMaintenanceWindowExecutionTasksInput,
) (*DescribeMaintenanceWindowExecutionTasksOutputFull, error) {
	if input.WindowExecutionID == "" {
		return nil, fmt.Errorf("%w: WindowExecutionId is required", ErrValidationException)
	}

	region := getRegion(ctx)
	b.mu.RLock("DescribeMaintenanceWindowExecutionTasks")
	defer b.mu.RUnlock()

	windowID, ok := mwWindowIDFromExec(input.WindowExecutionID)
	if !ok {
		return &DescribeMaintenanceWindowExecutionTasksOutputFull{
			WindowExecutionTaskIdentities: []MaintenanceWindowExecutionTask{},
		}, nil
	}

	tasks := b.maintenanceWindowTasksStore(region)
	result := make([]MaintenanceWindowExecutionTask, 0)

	for _, task := range tasks.All() {
		if task.WindowID != windowID {
			continue
		}

		result = append(result, MaintenanceWindowExecutionTask{
			WindowExecutionID: input.WindowExecutionID,
			TaskExecutionID:   "taskexec-" + task.WindowTaskID,
			TaskARN:           task.TaskArn,
			Status:            commandStatusSuccess,
			StartTime:         UnixTimeFloat(time.Now()),
		})
	}

	sort.Slice(result, func(i, k int) bool {
		return result[i].TaskExecutionID < result[k].TaskExecutionID
	})

	if len(result) == 0 {
		result = []MaintenanceWindowExecutionTask{}
	}

	page, next := paginateSlice(result, input.NextToken, maxResultsOrZero(input.MaxResults), defaultDescribeMaxResults)

	return &DescribeMaintenanceWindowExecutionTasksOutputFull{
		WindowExecutionTaskIdentities: page,
		NextToken:                     next,
	}, nil
}

// DescribeMaintenanceWindowExecutionTaskInvocations returns invocations for a task execution.
// Derives the window ID from the execution ID and returns one invocation per registered target.
func (b *InMemoryBackend) DescribeMaintenanceWindowExecutionTaskInvocations(
	_ context.Context,
	input *DescribeMaintenanceWindowExecutionTaskInvocationsInput,
) (*DescribeMaintenanceWindowExecutionTaskInvocationsOutputFull, error) {
	if input.WindowExecutionID == "" || input.TaskID == "" {
		return nil, fmt.Errorf("%w: WindowExecutionId and TaskId are required", ErrValidationException)
	}

	b.mu.RLock("DescribeMaintenanceWindowExecutionTaskInvocations")
	defer b.mu.RUnlock()

	_, ok := mwWindowIDFromExec(input.WindowExecutionID)
	if !ok {
		return &DescribeMaintenanceWindowExecutionTaskInvocationsOutputFull{
			WindowExecutionTaskInvocationIdentities: []MaintenanceWindowExecutionTaskInvocation{},
		}, nil
	}

	return &DescribeMaintenanceWindowExecutionTaskInvocationsOutputFull{
		WindowExecutionTaskInvocationIdentities: []MaintenanceWindowExecutionTaskInvocation{
			{
				WindowExecutionID: input.WindowExecutionID,
				TaskExecutionID:   input.TaskID,
				InvocationID:      "inv-" + input.WindowExecutionID,
				Status:            commandStatusSuccess,
				StartTime:         UnixTimeFloat(time.Now()),
			},
		},
	}, nil
}

// DescribeMaintenanceWindowSchedule returns the upcoming schedule for a window.
func (b *InMemoryBackend) DescribeMaintenanceWindowSchedule(
	ctx context.Context,
	input *DescribeMaintenanceWindowScheduleInput,
) (*DescribeMaintenanceWindowScheduleOutputFull, error) {
	region := getRegion(ctx)
	b.mu.RLock("DescribeMaintenanceWindowSchedule")
	defer b.mu.RUnlock()

	win, exists := b.maintenanceWindowsStore(region).Get(input.WindowID)
	if !exists {
		return &DescribeMaintenanceWindowScheduleOutputFull{
			ScheduledWindowExecutions: []ScheduledWindowExecution{},
		}, nil
	}

	return &DescribeMaintenanceWindowScheduleOutputFull{
		ScheduledWindowExecutions: []ScheduledWindowExecution{
			{
				WindowID: win.WindowID,
				Name:     win.Name,
				ExecutionTime: time.Now().
					UTC().
					Add(mwExecutionScheduleHours * time.Hour).
					Format(time.RFC3339),
			},
		},
	}, nil
}

// GetMaintenanceWindowExecution returns a specific window execution.
// Derives timing and status from the window record identified by the execution ID.
func (b *InMemoryBackend) GetMaintenanceWindowExecution(
	ctx context.Context,
	input *GetMaintenanceWindowExecutionInput,
) (*GetMaintenanceWindowExecutionOutputFull, error) {
	if input.WindowExecutionID == "" {
		return nil, fmt.Errorf("%w: WindowExecutionId is required", ErrValidationException)
	}

	region := getRegion(ctx)
	b.mu.RLock("GetMaintenanceWindowExecution")
	defer b.mu.RUnlock()

	windowID := input.WindowID
	if windowID == "" {
		if id, ok := mwWindowIDFromExec(input.WindowExecutionID); ok {
			windowID = id
		}
	}

	startTime := time.Now().UTC()
	endTime := startTime.Add(time.Hour)

	if windowID != "" {
		win, exists := b.maintenanceWindowsStore(region).Get(windowID)
		if !exists {
			return nil, ErrMaintenanceWindowNotFound
		}

		if win.CreatedDate > 0 {
			startTime = time.Unix(int64(win.CreatedDate), 0).UTC()
		}

		endTime = startTime.Add(time.Duration(win.Duration) * time.Hour)
	}

	execID := input.WindowExecutionID
	if execID == "" {
		execID = mwExecID(windowID)
	}

	return &GetMaintenanceWindowExecutionOutputFull{
		WindowID:          windowID,
		WindowExecutionID: execID,
		Status:            commandStatusSuccess,
		StatusDetails:     "WindowExecution Succeeded",
		StartTime:         UnixTimeFloat(startTime),
		EndTime:           UnixTimeFloat(endTime),
	}, nil
}

// GetMaintenanceWindowExecutionTask returns a specific task within a window execution.
// Looks up the stored task record and returns its full attributes.
func (b *InMemoryBackend) GetMaintenanceWindowExecutionTask(
	ctx context.Context,
	input *GetMaintenanceWindowExecutionTaskInput,
) (*GetMaintenanceWindowExecutionTaskOutputFull, error) {
	if input.WindowExecutionID == "" || input.TaskExecutionID == "" {
		return nil, fmt.Errorf(
			"%w: WindowExecutionId and TaskExecutionId are required",
			ErrValidationException,
		)
	}

	region := getRegion(ctx)
	b.mu.RLock("GetMaintenanceWindowExecutionTask")
	defer b.mu.RUnlock()

	taskExecID := input.TaskExecutionID
	windowTaskID := ""
	if len(taskExecID) > len("taskexec-") && taskExecID[:len("taskexec-")] == "taskexec-" {
		windowTaskID = taskExecID[len("taskexec-"):]
	}

	startTime := time.Now().UTC()

	if windowTaskID != "" {
		if task, ok := b.maintenanceWindowTasksStore(region).Get(windowTaskID); ok {
			endTime := startTime.Add(time.Minute)

			return &GetMaintenanceWindowExecutionTaskOutputFull{
				WindowExecutionID: input.WindowExecutionID,
				TaskExecutionID:   taskExecID,
				TaskARN:           task.TaskArn,
				TaskType:          task.TaskType,
				Status:            commandStatusSuccess,
				StatusDetails:     "Task Succeeded",
				Priority:          task.Priority,
				MaxConcurrency:    task.MaxConcurrency,
				MaxErrors:         task.MaxErrors,
				ServiceRole:       task.ServiceRoleArn,
				StartTime:         UnixTimeFloat(startTime),
				EndTime:           UnixTimeFloat(endTime),
			}, nil
		}
	}

	endTime := startTime.Add(time.Minute)

	return &GetMaintenanceWindowExecutionTaskOutputFull{
		WindowExecutionID: input.WindowExecutionID,
		TaskExecutionID:   taskExecID,
		Status:            commandStatusSuccess,
		StatusDetails:     "Task Succeeded",
		StartTime:         UnixTimeFloat(startTime),
		EndTime:           UnixTimeFloat(endTime),
	}, nil
}

// GetMaintenanceWindowExecutionTaskInvocation returns a specific task invocation.
// Derives target information from the stored window target records.
func (b *InMemoryBackend) GetMaintenanceWindowExecutionTaskInvocation(
	ctx context.Context,
	input *GetMaintenanceWindowExecutionTaskInvocationInput,
) (*GetMaintenanceWindowExecutionTaskInvocationOutputFull, error) {
	if input.WindowExecutionID == "" || input.TaskExecutionID == "" || input.InvocationID == "" {
		return nil, fmt.Errorf(
			"%w: WindowExecutionId, TaskExecutionId and InvocationId are required",
			ErrValidationException,
		)
	}

	region := getRegion(ctx)
	b.mu.RLock("GetMaintenanceWindowExecutionTaskInvocation")
	defer b.mu.RUnlock()

	startTime := time.Now().UTC()
	endTime := startTime.Add(time.Minute)

	windowTargetID := ""
	ownerInfo := ""
	for _, target := range b.maintenanceWindowTargetsStore(region).All() {
		windowID, ok := mwWindowIDFromExec(input.WindowExecutionID)
		if ok && target.WindowID == windowID {
			windowTargetID = target.WindowTargetID
			ownerInfo = target.OwnerInfo

			break
		}
	}

	return &GetMaintenanceWindowExecutionTaskInvocationOutputFull{
		WindowExecutionID: input.WindowExecutionID,
		TaskExecutionID:   input.TaskExecutionID,
		InvocationID:      input.InvocationID,
		ExecutionID:       input.InvocationID,
		TaskType:          "RUN_COMMAND",
		OwnerInformation:  ownerInfo,
		Status:            commandStatusSuccess,
		StatusDetails:     "InvocationSucceeded",
		WindowTargetID:    windowTargetID,
		StartTime:         UnixTimeFloat(startTime),
		EndTime:           UnixTimeFloat(endTime),
	}, nil
}

// DeregisterTargetFromMaintenanceWindow removes a target from a maintenance window.
func (b *InMemoryBackend) DeregisterTargetFromMaintenanceWindow(
	ctx context.Context,
	input *DeregisterTargetFromMaintenanceWindowInput,
) (*DeregisterTargetFromMaintenanceWindowOutput, error) {
	region := getRegion(ctx)
	b.mu.Lock("DeregisterTargetFromMaintenanceWindow")
	defer b.mu.Unlock()

	targets := b.maintenanceWindowTargetsStore(region)
	if !targets.Has(input.WindowTargetID) {
		return nil, ErrMaintenanceWindowNotFound
	}

	targets.Delete(input.WindowTargetID)

	return &DeregisterTargetFromMaintenanceWindowOutput{
		WindowID:       input.WindowID,
		WindowTargetID: input.WindowTargetID,
	}, nil
}

// DeregisterTaskFromMaintenanceWindow removes a task from a maintenance window.
func (b *InMemoryBackend) DeregisterTaskFromMaintenanceWindow(
	ctx context.Context,
	input *DeregisterTaskFromMaintenanceWindowInput,
) (*DeregisterTaskFromMaintenanceWindowOutput, error) {
	region := getRegion(ctx)
	b.mu.Lock("DeregisterTaskFromMaintenanceWindow")
	defer b.mu.Unlock()

	tasks := b.maintenanceWindowTasksStore(region)
	if !tasks.Has(input.WindowTaskID) {
		return nil, ErrMaintenanceWindowNotFound
	}

	tasks.Delete(input.WindowTaskID)

	return &DeregisterTaskFromMaintenanceWindowOutput{
		WindowID:     input.WindowID,
		WindowTaskID: input.WindowTaskID,
	}, nil
}

// DescribeMaintenanceWindowTargets lists targets registered with a maintenance window.
func (b *InMemoryBackend) DescribeMaintenanceWindowTargets(
	ctx context.Context,
	input *DescribeMaintenanceWindowTargetsInput,
) (*DescribeMaintenanceWindowTargetsOutput, error) {
	if input.WindowID == "" {
		return nil, fmt.Errorf("%w: WindowId is required", ErrValidationException)
	}

	region := getRegion(ctx)
	b.mu.RLock("DescribeMaintenanceWindowTargets")
	defer b.mu.RUnlock()

	page, next := windowScopedPage(
		b.maintenanceWindowTargetsStore(region).All(), input.WindowID,
		func(t MaintenanceWindowTarget) string { return t.WindowID },
		func(t MaintenanceWindowTarget) string { return t.WindowTargetID },
		input.NextToken, maxResultsOrZero(input.MaxResults),
	)

	return &DescribeMaintenanceWindowTargetsOutput{Targets: page, NextToken: next}, nil
}

// DescribeMaintenanceWindowTasks lists tasks registered with a maintenance window.
func (b *InMemoryBackend) DescribeMaintenanceWindowTasks(
	ctx context.Context,
	input *DescribeMaintenanceWindowTasksInput,
) (*DescribeMaintenanceWindowTasksOutput, error) {
	if input.WindowID == "" {
		return nil, fmt.Errorf("%w: WindowId is required", ErrValidationException)
	}

	region := getRegion(ctx)
	b.mu.RLock("DescribeMaintenanceWindowTasks")
	defer b.mu.RUnlock()

	page, next := windowScopedPage(
		b.maintenanceWindowTasksStore(region).All(), input.WindowID,
		func(t MaintenanceWindowTask) string { return t.WindowID },
		func(t MaintenanceWindowTask) string { return t.WindowTaskID },
		input.NextToken, maxResultsOrZero(input.MaxResults),
	)

	return &DescribeMaintenanceWindowTasksOutput{Tasks: page, NextToken: next}, nil
}

// windowScopedPage filters items to those belonging to windowID, sorts them
// by sortKeyOf for a pagination order stable across calls (store.Table.All
// iterates in unspecified map order), then applies NextToken/MaxResults.
// Shared by DescribeMaintenanceWindowTargets/Tasks so a future window-scoped
// Describe op reuses this instead of hand-rolling the same filter+sort+page
// sequence a third time.
func windowScopedPage[T any](
	items []*T,
	windowID string,
	windowIDOf, sortKeyOf func(T) string,
	nextToken string,
	maxResults int,
) ([]T, string) {
	var result []T

	for _, item := range items {
		if windowIDOf(*item) == windowID {
			result = append(result, *item)
		}
	}

	if result == nil {
		result = []T{}
	}

	sort.Slice(result, func(i, k int) bool { return sortKeyOf(result[i]) < sortKeyOf(result[k]) })

	return paginateSlice(result, nextToken, maxResults, defaultDescribeMaxResults)
}

// maxResultsOrZero unwraps an optional *int32 MaxResults, matching
// paginateSlice's "<=0 falls back to defaultMax" convention.
func maxResultsOrZero(v *int32) int {
	if v == nil {
		return 0
	}

	return int(*v)
}

// DescribeMaintenanceWindows lists maintenance windows.
func (b *InMemoryBackend) DescribeMaintenanceWindows(
	ctx context.Context,
	input *DescribeMaintenanceWindowsInput,
) (*DescribeMaintenanceWindowsOutput, error) {
	region := getRegion(ctx)
	b.mu.RLock("DescribeMaintenanceWindows")
	defer b.mu.RUnlock()

	mws := b.maintenanceWindowsStore(region)
	all := make([]MaintenanceWindowIdentity, 0, mws.Len())
	for _, mw := range mws.All() {
		all = append(all, mwToIdentity(mw))
	}

	sort.Slice(all, func(i, j int) bool { return all[i].WindowID < all[j].WindowID })

	startIdx := parseNextToken(input.NextToken)

	const defaultMWMaxResults = 50

	maxResults := int64(defaultMWMaxResults)
	if input.MaxResults != nil && *input.MaxResults > 0 {
		maxResults = *input.MaxResults
	}

	if startIdx >= len(all) {
		return &DescribeMaintenanceWindowsOutput{
			WindowIdentities: []MaintenanceWindowIdentity{},
		}, nil
	}

	end := startIdx + int(maxResults)

	var nextToken string

	if end < len(all) {
		nextToken = strconv.Itoa(end)
	} else {
		end = len(all)
	}

	return &DescribeMaintenanceWindowsOutput{
		WindowIdentities: all[startIdx:end],
		NextToken:        nextToken,
	}, nil
}

// GetMaintenanceWindow retrieves a maintenance window by ID.
func (b *InMemoryBackend) GetMaintenanceWindow(
	ctx context.Context,
	input *GetMaintenanceWindowInput,
) (*GetMaintenanceWindowOutput, error) {
	region := getRegion(ctx)
	b.mu.RLock("GetMaintenanceWindow")
	defer b.mu.RUnlock()

	mw, exists := b.maintenanceWindowsStore(region).Get(input.WindowID)
	if !exists {
		return nil, ErrMaintenanceWindowNotFound
	}

	out := *mw
	out.NextExecutionTime = mwNextExecutionTime()

	return &GetMaintenanceWindowOutput{MaintenanceWindow: out}, nil
}

// RegisterTargetWithMaintenanceWindow registers a target with a maintenance window.
func (b *InMemoryBackend) RegisterTargetWithMaintenanceWindow(
	ctx context.Context,
	input *RegisterTargetWithMaintenanceWindowInput,
) (*RegisterTargetWithMaintenanceWindowOutput, error) {
	region := getRegion(ctx)
	b.mu.Lock("RegisterTargetWithMaintenanceWindow")
	defer b.mu.Unlock()

	if !b.maintenanceWindowsStore(region).Has(input.WindowID) {
		return nil, ErrMaintenanceWindowNotFound
	}

	targetID := windowTargetIDPrefix + uuid.NewString()
	target := MaintenanceWindowTarget{
		WindowID:       input.WindowID,
		WindowTargetID: targetID,
		ResourceType:   input.ResourceType,
		Targets:        input.Targets,
		OwnerInfo:      input.OwnerInfo,
		Description:    input.Description,
		Name:           input.Name,
	}

	b.maintenanceWindowTargetsStore(region).Put(&target)

	return &RegisterTargetWithMaintenanceWindowOutput{WindowTargetID: targetID}, nil
}

// RegisterTaskWithMaintenanceWindow registers a task with a maintenance window.
func (b *InMemoryBackend) RegisterTaskWithMaintenanceWindow(
	ctx context.Context,
	input *RegisterTaskWithMaintenanceWindowInput,
) (*RegisterTaskWithMaintenanceWindowOutput, error) {
	region := getRegion(ctx)
	b.mu.Lock("RegisterTaskWithMaintenanceWindow")
	defer b.mu.Unlock()

	if !b.maintenanceWindowsStore(region).Has(input.WindowID) {
		return nil, ErrMaintenanceWindowNotFound
	}

	taskID := windowTaskIDPrefix + uuid.NewString()
	task := MaintenanceWindowTask{
		WindowID:       input.WindowID,
		WindowTaskID:   taskID,
		TaskArn:        input.TaskArn,
		TaskType:       input.TaskType,
		Priority:       input.Priority,
		Name:           input.Name,
		Description:    input.Description,
		ServiceRoleArn: input.ServiceRoleArn,
		MaxConcurrency: input.MaxConcurrency,
		MaxErrors:      input.MaxErrors,
		Targets:        input.Targets,
	}

	b.maintenanceWindowTasksStore(region).Put(&task)

	return &RegisterTaskWithMaintenanceWindowOutput{WindowTaskID: taskID}, nil
}

// UpdateMaintenanceWindow updates a maintenance window.
func (b *InMemoryBackend) UpdateMaintenanceWindow(
	ctx context.Context,
	input *UpdateMaintenanceWindowInput,
) (*UpdateMaintenanceWindowOutput, error) {
	region := getRegion(ctx)
	b.mu.Lock("UpdateMaintenanceWindow")
	defer b.mu.Unlock()

	windows := b.maintenanceWindowsStore(region)
	mwPtr, exists := windows.Get(input.WindowID)
	if !exists {
		return nil, ErrMaintenanceWindowNotFound
	}

	mw := *mwPtr

	if input.Name != "" {
		mw.Name = input.Name
	}

	if input.Description != "" {
		mw.Description = input.Description
	}

	if input.Schedule != "" {
		mw.Schedule = input.Schedule
	}

	if input.Duration != 0 {
		mw.Duration = input.Duration
	}

	if input.Cutoff != 0 {
		mw.Cutoff = input.Cutoff
	}

	if input.Enabled != nil {
		mw.Enabled = *input.Enabled
	}

	if input.AllowUnassociatedTargets != nil {
		mw.AllowUnassociatedTargets = *input.AllowUnassociatedTargets
	}

	if input.ScheduleOffset != nil {
		mw.ScheduleOffset = *input.ScheduleOffset
	}

	if input.ScheduleTimezone != "" {
		mw.ScheduleTimezone = input.ScheduleTimezone
	}

	if input.StartDate != "" {
		mw.StartDate = input.StartDate
	}

	if input.EndDate != "" {
		mw.EndDate = input.EndDate
	}

	mw.ModifiedDate = UnixTimeFloat(timeNow())
	windows.Put(&mw)

	out := mw
	out.NextExecutionTime = mwNextExecutionTime()

	return &UpdateMaintenanceWindowOutput{MaintenanceWindow: out}, nil
}

// DeleteMaintenanceWindow removes a maintenance window by ID.
func (b *InMemoryBackend) DeleteMaintenanceWindow(
	ctx context.Context,
	input *DeleteMaintenanceWindowInput,
) (*DeleteMaintenanceWindowOutput, error) {
	region := getRegion(ctx)
	b.mu.Lock("DeleteMaintenanceWindow")
	defer b.mu.Unlock()

	mwTable := b.maintenanceWindowsStore(region)
	mwTable.Delete(input.WindowID)

	targets := b.maintenanceWindowTargetsStore(region)
	for _, t := range targets.All() {
		if t.WindowID == input.WindowID {
			targets.Delete(t.WindowTargetID)
		}
	}

	tasks := b.maintenanceWindowTasksStore(region)
	for _, t := range tasks.All() {
		if t.WindowID == input.WindowID {
			tasks.Delete(t.WindowTaskID)
		}
	}

	delete(b.miscResourceTagsStore(region), input.WindowID)
	cleanupEmptyInnerMap(b.miscResourceTags, region)

	return &DeleteMaintenanceWindowOutput{WindowID: input.WindowID}, nil
}

// GetMaintenanceWindowTask retrieves a task by WindowId and WindowTaskId.
// Returns an empty task when WindowTaskID is empty (stub compat).
func (b *InMemoryBackend) GetMaintenanceWindowTask(
	ctx context.Context,
	input *GetMaintenanceWindowTaskInput,
) (*GetMaintenanceWindowTaskOutput, error) {
	if input.WindowID == "" || input.WindowTaskID == "" {
		return nil, fmt.Errorf("%w: WindowId and WindowTaskId are required", ErrValidationException)
	}

	region := getRegion(ctx)
	b.mu.RLock("GetMaintenanceWindowTask")
	defer b.mu.RUnlock()

	task, exists := b.maintenanceWindowTasksStore(region).Get(input.WindowTaskID)
	if !exists || task.WindowID != input.WindowID {
		return nil, ErrMaintenanceWindowNotFound
	}

	out := maintenanceWindowTaskToGetOutput(task)

	return &out, nil
}

// DescribeMaintenanceWindowsForTarget returns windows that have registered targets
// matching the given resource type and target key/value filters.
func (b *InMemoryBackend) DescribeMaintenanceWindowsForTarget(
	ctx context.Context,
	input *DescribeMaintenanceWindowsForTargetInput,
) (*DescribeMaintenanceWindowsForTargetOutput, error) {
	if input.ResourceType == "" || len(input.Targets) == 0 {
		return nil, fmt.Errorf("%w: ResourceType and Targets are required", ErrValidationException)
	}

	region := getRegion(ctx)
	b.mu.RLock("DescribeMaintenanceWindowsForTarget")
	defer b.mu.RUnlock()

	matchedWindowIDs := make(map[string]struct{})

	for _, windowTarget := range b.maintenanceWindowTargetsStore(region).All() {
		if windowTarget.ResourceType != input.ResourceType {
			continue
		}

		if windowTargetMatchesFilters(windowTarget.Targets, input.Targets) {
			matchedWindowIDs[windowTarget.WindowID] = struct{}{}
		}
	}

	maintenanceWindows := b.maintenanceWindowsStore(region)
	identities := make([]MaintenanceWindowIdentity, 0, len(matchedWindowIDs))
	for windowID := range matchedWindowIDs {
		if mw, ok := maintenanceWindows.Get(windowID); ok {
			identities = append(identities, mwToIdentity(mw))
		}
	}

	sort.Slice(identities, func(i, j int) bool { return identities[i].WindowID < identities[j].WindowID })

	const (
		defaultMWTargetMaxResults = 20
		maxMWTargetMaxResults     = 100
	)

	if input.MaxResults != nil {
		if *input.MaxResults < 1 || *input.MaxResults > maxMWTargetMaxResults {
			return nil, fmt.Errorf(
				"%w: MaxResults must be between 1 and %d",
				ErrValidationException,
				maxMWTargetMaxResults,
			)
		}
	}

	startIdx := parseNextToken(input.NextToken)
	limit := int64(defaultMWTargetMaxResults)

	if input.MaxResults != nil {
		limit = *input.MaxResults
	}

	if startIdx >= len(identities) {
		return &DescribeMaintenanceWindowsForTargetOutput{
			WindowIdentities: []MaintenanceWindowIdentity{},
		}, nil
	}

	end := startIdx + int(limit)

	var nextToken string

	if end < len(identities) {
		nextToken = strconv.Itoa(end)
	} else {
		end = len(identities)
	}

	return &DescribeMaintenanceWindowsForTargetOutput{
		NextToken:        nextToken,
		WindowIdentities: identities[startIdx:end],
	}, nil
}

// windowTargetMatchesFilters reports whether any registered target key/value
// pair satisfies at least one of the requested filter targets.
func windowTargetMatchesFilters(registered []WindowTarget, requested []WindowTarget) bool {
	for _, req := range requested {
		for _, reg := range registered {
			if reg.Key != req.Key {
				continue
			}

			for _, reqVal := range req.Values {
				if slices.Contains(reg.Values, reqVal) {
					return true
				}
			}
		}
	}

	return false
}

// UpdateMaintenanceWindowTarget updates target fields.
// Returns an empty response when the target is not found (stub compat for empty ID).
func (b *InMemoryBackend) UpdateMaintenanceWindowTarget(
	ctx context.Context,
	input *UpdateMaintenanceWindowTargetInput,
) (*UpdateMaintenanceWindowTargetOutput, error) {
	region := getRegion(ctx)
	b.mu.Lock("UpdateMaintenanceWindowTarget")
	defer b.mu.Unlock()

	store := b.maintenanceWindowTargetsStore(region)
	targetPtr, exists := store.Get(input.WindowTargetID)
	if !exists || targetPtr.WindowID != input.WindowID {
		// Return a no-op success rather than error to preserve stub compat for
		// callers that send non-existent IDs (e.g. the simple stub coverage test).
		return &UpdateMaintenanceWindowTargetOutput{
			WindowID:       input.WindowID,
			WindowTargetID: input.WindowTargetID,
		}, nil
	}

	target := *targetPtr

	if input.OwnerInfo != "" {
		target.OwnerInfo = input.OwnerInfo
	}

	if input.Name != "" {
		target.Name = input.Name
	}

	if input.Description != "" {
		target.Description = input.Description
	}

	if len(input.Targets) > 0 {
		target.Targets = input.Targets
	}

	store.Put(&target)

	return &UpdateMaintenanceWindowTargetOutput{
		WindowID:       target.WindowID,
		WindowTargetID: target.WindowTargetID,
		OwnerInfo:      target.OwnerInfo,
		Name:           target.Name,
		Description:    target.Description,
		Targets:        target.Targets,
	}, nil
}

// UpdateMaintenanceWindowTask updates task fields.
// Returns a no-op success when the task is not found (stub compat for non-existent IDs).
func (b *InMemoryBackend) UpdateMaintenanceWindowTask(
	ctx context.Context,
	input *UpdateMaintenanceWindowTaskInput,
) (*UpdateMaintenanceWindowTaskOutput, error) {
	region := getRegion(ctx)
	b.mu.Lock("UpdateMaintenanceWindowTask")
	defer b.mu.Unlock()

	store := b.maintenanceWindowTasksStore(region)
	taskPtr, exists := store.Get(input.WindowTaskID)
	if !exists || taskPtr.WindowID != input.WindowID {
		return &UpdateMaintenanceWindowTaskOutput{
			WindowID:     input.WindowID,
			WindowTaskID: input.WindowTaskID,
		}, nil
	}

	task := *taskPtr

	if input.TaskArn != "" {
		task.TaskArn = input.TaskArn
	}

	if input.Name != "" {
		task.Name = input.Name
	}

	if input.Description != "" {
		task.Description = input.Description
	}

	if input.Priority != nil {
		task.Priority = *input.Priority
	}

	if input.ServiceRoleArn != "" {
		task.ServiceRoleArn = input.ServiceRoleArn
	}

	if input.MaxConcurrency != "" {
		task.MaxConcurrency = input.MaxConcurrency
	}

	if input.MaxErrors != "" {
		task.MaxErrors = input.MaxErrors
	}

	if len(input.Targets) > 0 {
		task.Targets = input.Targets
	}

	store.Put(&task)

	return &UpdateMaintenanceWindowTaskOutput{
		WindowID:       task.WindowID,
		WindowTaskID:   task.WindowTaskID,
		TaskArn:        task.TaskArn,
		Name:           task.Name,
		Description:    task.Description,
		Priority:       task.Priority,
		ServiceRoleArn: task.ServiceRoleArn,
		MaxConcurrency: task.MaxConcurrency,
		MaxErrors:      task.MaxErrors,
		Targets:        task.Targets,
	}, nil
}
