package iot

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"time"

	"github.com/google/uuid"

	"github.com/blackbirdworks/gopherstack/pkgs/arn"
)

// fakePEM is a minimal fake PEM certificate returned by CreateCertificateFromCsr and RegisterCertificate.
const fakePEM = `-----BEGIN CERTIFICATE-----
MIICpDCCAYwCCQDU+pQ4pHgSpDANBgkqhkiG9w0BAQsFADAUMRIwEAYDVQQDDAls
b2NhbGhvc3QwHhcNMjMwMTAxMDAwMDAwWhcNMjQwMTAxMDAwMDAwWjAUMRIwEAYD
VQQDDAlsb2NhbGhvc3QwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC7
o4qne60TB3wolFl6qADvFVMZUDCwJJlFBMDkajIxpQFNbBgxDuAQFV8AAAAAAA==
-----END CERTIFICATE-----`

// certIDHexLen is the number of bytes (half the hex char count) for a certificate ID.
const certIDHexLen = 32 // produces a 64-char hex string

// certStatusActive is the AWS IoT certificate ACTIVE status value.
const certStatusActive = "ACTIVE"

// certStatusInactive is the AWS IoT certificate INACTIVE status value.
const certStatusInactive = "INACTIVE"

// certStatusPendingTransfer is the AWS IoT certificate PENDING_TRANSFER status value.
const certStatusPendingTransfer = "PENDING_TRANSFER"

// certStatusRevoked is the AWS IoT certificate REVOKED status value.
const certStatusRevoked = "REVOKED"

// certStatusPendingActivation is the AWS IoT certificate PENDING_ACTIVATION status value.
const certStatusPendingActivation = "PENDING_ACTIVATION"

// provisioningClaimTTL is the fleet-provisioning claim certificate lifetime.
const provisioningClaimTTL = 5 * time.Minute

// certModeDefault is the AWS IoT CertificateMode value for certificates
// generated by AWS IoT Core or registered with an issuer CA.
const certModeDefault = "DEFAULT"

// certModeSNIOnly is the AWS IoT CertificateMode value for certificates
// registered without an issuer CA (RegisterCertificateWithoutCA).
const certModeSNIOnly = "SNI_ONLY"

// certValidityPeriod is the fake validity window applied to generated/registered
// certificates (real AWS derives this from the X.509 cert itself; this mock
// backend doesn't parse PEM, so it fabricates a plausible one-year window).
const certValidityPeriod = 365 * 24 * time.Hour

// initialCustomerVersion is the CustomerVersion assigned to a certificate at
// creation/registration time. AWS increments it on certain certificate
// rotation operations; this backend increments it on UpdateCertificate.
const initialCustomerVersion = 1

// randomHex generates a cryptographically random hex string of n bytes (2n characters).
func randomHex(n int) string {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		panic("iot: randomHex: crypto/rand failed: " + err.Error())
	}

	return hex.EncodeToString(b)
}

// AddCertificateInternal seeds a Certificate with a caller-chosen
// CertificateID directly into the backend for testing (mirrors
// AddThingInternal). RegisterCertificate/CreateCertificateFromCsr always
// generate a random 64-hex-char ID, so tests that need a deterministic,
// human-readable certificate ID (e.g. to assert on it in a URL path) use
// this instead.
func (b *InMemoryBackend) AddCertificateInternal(c Certificate) {
	b.mu.Lock()
	defer b.mu.Unlock()

	if c.ARN == "" {
		c.ARN = arn.Build("iot", b.region, b.accountID, fmt.Sprintf("cert/%s", c.CertificateID))
	}

	if c.CreatedAt.IsZero() {
		c.CreatedAt = time.Now()
	}

	if c.LastModifiedAt.IsZero() {
		c.LastModifiedAt = c.CreatedAt
	}

	if c.OwnedBy == "" {
		c.OwnedBy = b.accountID
	}

	cp := c
	b.certificates.Put(&cp)
}

// AddCACertificateInternal seeds a CACertificate with a caller-chosen
// CertificateID directly into the backend for testing (mirrors
// AddCertificateInternal), letting tests set CreationDate/RegistrationConfig
// explicitly without going through RegisterCACertificate's real-time clock.
func (b *InMemoryBackend) AddCACertificateInternal(c CACertificate) {
	b.mu.Lock()
	defer b.mu.Unlock()

	if c.CertificateARN == "" {
		c.CertificateARN = b.caCertARN(c.CertificateID)
	}

	if c.Status == "" {
		c.Status = statusActive
	}

	if c.OwnedBy == "" {
		c.OwnedBy = b.accountID
	}

	cp := c
	b.caCertificates.Put(&cp)
}

// newCertificate creates a new Certificate with a random 64-hex-char ID.
func (b *InMemoryBackend) newCertificate(pem, status, mode string) *Certificate {
	certID := randomHex(certIDHexLen)
	arn := arn.Build("iot", b.region, b.accountID, fmt.Sprintf("cert/%s", certID))
	now := time.Now()

	return &Certificate{
		CertificateID:     certID,
		ARN:               arn,
		Status:            status,
		PEM:               pem,
		CreatedAt:         now,
		LastModifiedAt:    now,
		ValidityNotBefore: now,
		ValidityNotAfter:  now.Add(certValidityPeriod),
		OwnedBy:           b.accountID,
		GenerationID:      uuid.NewString(),
		CertificateMode:   mode,
		CustomerVersion:   initialCustomerVersion,
	}
}

// CreateCertificateFromCsr creates a new certificate from a CSR.
func (b *InMemoryBackend) CreateCertificateFromCsr(input *CreateCertificateFromCsrInput) (*Certificate, error) {
	b.mu.Lock()
	defer b.mu.Unlock()

	status := certStatusInactive
	if input.SetAsActive {
		status = certStatusActive
	}

	cert := b.newCertificate(fakePEM, status, certModeDefault)
	b.certificates.Put(cert)

	return cert, nil
}

// RegisterCertificate registers a certificate.
func (b *InMemoryBackend) RegisterCertificate(input *RegisterCertificateInput) (*Certificate, error) {
	b.mu.Lock()
	defer b.mu.Unlock()

	status := input.Status
	if status == "" {
		status = certStatusInactive
	}

	pem := input.CertificatePem
	if pem == "" {
		pem = fakePEM
	}

	cert := b.newCertificate(pem, status, certModeDefault)
	b.certificates.Put(cert)

	return cert, nil
}

// RegisterCertificateWithoutCA registers a certificate without a CA. Per AWS
// IoT, certificates registered this way are always in SNI_ONLY mode (they
// have no issuer CA on file), unlike RegisterCertificate.
func (b *InMemoryBackend) RegisterCertificateWithoutCA(input *RegisterCertificateInput) (*Certificate, error) {
	b.mu.Lock()
	defer b.mu.Unlock()

	status := input.Status
	if status == "" {
		status = certStatusInactive
	}

	pem := input.CertificatePem
	if pem == "" {
		pem = fakePEM
	}

	cert := b.newCertificate(pem, status, certModeSNIOnly)
	b.certificates.Put(cert)

	return cert, nil
}

// DescribeCertificate returns a Certificate by ID.
func (b *InMemoryBackend) DescribeCertificate(certificateID string) (*Certificate, error) {
	b.mu.RLock()
	defer b.mu.RUnlock()

	cert, ok := b.certificates.Get(certificateID)
	if !ok {
		return nil, fmt.Errorf("%w: %s", ErrCertificateNotFound, certificateID)
	}

	cp := *cert

	return &cp, nil
}

// ListCertificates returns all certificates sorted by ID.
func (b *InMemoryBackend) ListCertificates() []*Certificate {
	b.mu.RLock()
	defer b.mu.RUnlock()

	items := b.certificates.Snapshot()
	out := make([]*Certificate, 0, len(items))

	for _, v := range items {
		cp := *v
		out = append(out, &cp)
	}

	return out
}

// isValidCertStatus reports whether s is a legal AWS IoT certificate status.
func isValidCertStatus(s string) bool {
	switch s {
	case certStatusActive, certStatusInactive, certStatusRevoked,
		certStatusPendingTransfer, certStatusPendingActivation:
		return true
	}

	return false
}

// UpdateCertificate updates the status of a certificate.
func (b *InMemoryBackend) UpdateCertificate(input *UpdateCertificateInput) error {
	switch input.NewStatus {
	case certStatusPendingTransfer, certStatusPendingActivation:
		return fmt.Errorf("%w: status %q cannot be set via UpdateCertificate", ErrValidation, input.NewStatus)
	}

	if input.NewStatus != "" && !isValidCertStatus(input.NewStatus) {
		return fmt.Errorf("%w: invalid certificate status %q", ErrValidation, input.NewStatus)
	}

	b.mu.Lock()
	defer b.mu.Unlock()

	cert, ok := b.certificates.Get(input.CertificateID)
	if !ok {
		return fmt.Errorf("%w: %s", ErrCertificateNotFound, input.CertificateID)
	}

	cert.Status = input.NewStatus
	cert.LastModifiedAt = time.Now()
	cert.CustomerVersion++

	return nil
}

// DeleteCertificate deletes a certificate by ID.
func (b *InMemoryBackend) DeleteCertificate(certificateID string) error {
	b.mu.Lock()
	defer b.mu.Unlock()

	cert, ok := b.certificates.Get(certificateID)
	if !ok {
		return fmt.Errorf("%w: %s", ErrCertificateNotFound, certificateID)
	}

	if cert.Status == certStatusActive {
		return fmt.Errorf("%w: certificate %q must be deactivated before deletion", ErrDeleteConflict, certificateID)
	}

	b.certificates.Delete(certificateID)

	return nil
}

// CreateCertificateProvider creates a new certificate provider.
func (b *InMemoryBackend) CreateCertificateProvider(
	input *CreateCertificateProviderInput,
) (*CertificateProvider, error) {
	if input.CertificateProviderName == "" {
		return nil, fmt.Errorf("%w: CertificateProviderName is required", ErrValidation)
	}

	b.mu.Lock()
	defer b.mu.Unlock()

	if b.certificateProviders.Has(input.CertificateProviderName) {
		return nil, fmt.Errorf("%w: certificate provider %q already exists",
			ErrAlreadyExists, input.CertificateProviderName)
	}

	arn := arn.Build("iot", b.region, b.accountID,
		fmt.Sprintf("certificateprovider/%s", input.CertificateProviderName))

	ops := make([]string, len(input.AccountDefaultForOperations))
	copy(ops, input.AccountDefaultForOperations)

	cp := &CertificateProvider{
		CertificateProviderName:     input.CertificateProviderName,
		ARN:                         arn,
		LambdaFunctionARN:           input.LambdaFunctionARN,
		AccountDefaultForOperations: ops,
		CreatedAt:                   time.Now(),
		LastModifiedAt:              time.Now(),
	}

	b.certificateProviders.Put(cp)
	b.putResourceTagsLocked(cp.ARN, input.Tags)

	return cp, nil
}

// DescribeCertificateProvider returns a certificate provider by name.
func (b *InMemoryBackend) DescribeCertificateProvider(name string) (*CertificateProvider, error) {
	b.mu.RLock()
	defer b.mu.RUnlock()

	cp, ok := b.certificateProviders.Get(name)
	if !ok {
		return nil, fmt.Errorf("%w: %s", ErrCertificateProviderNotFound, name)
	}

	result := *cp
	result.AccountDefaultForOperations = make([]string, len(cp.AccountDefaultForOperations))
	copy(result.AccountDefaultForOperations, cp.AccountDefaultForOperations)

	return &result, nil
}

// ListCertificateProviders returns all certificate providers sorted by name.
func (b *InMemoryBackend) ListCertificateProviders() []*CertificateProvider {
	b.mu.RLock()
	defer b.mu.RUnlock()

	items := b.certificateProviders.Snapshot()
	out := make([]*CertificateProvider, 0, len(items))

	for _, v := range items {
		cp := *v
		cp.AccountDefaultForOperations = make([]string, len(v.AccountDefaultForOperations))
		copy(cp.AccountDefaultForOperations, v.AccountDefaultForOperations)
		out = append(out, &cp)
	}

	return out
}

// UpdateCertificateProvider updates an existing certificate provider.
func (b *InMemoryBackend) UpdateCertificateProvider(input *UpdateCertificateProviderInput) error {
	b.mu.Lock()
	defer b.mu.Unlock()

	cp, ok := b.certificateProviders.Get(input.CertificateProviderName)
	if !ok {
		return fmt.Errorf("%w: %s", ErrCertificateProviderNotFound, input.CertificateProviderName)
	}

	if input.LambdaFunctionARN != "" {
		cp.LambdaFunctionARN = input.LambdaFunctionARN
	}

	if input.AccountDefaultForOperations != nil {
		ops := make([]string, len(input.AccountDefaultForOperations))
		copy(ops, input.AccountDefaultForOperations)
		cp.AccountDefaultForOperations = ops
	}

	cp.LastModifiedAt = time.Now()

	return nil
}

// DeleteCertificateProvider deletes a certificate provider by name.
func (b *InMemoryBackend) DeleteCertificateProvider(name string) error {
	b.mu.Lock()
	defer b.mu.Unlock()

	if !b.certificateProviders.Has(name) {
		return fmt.Errorf("%w: %s", ErrCertificateProviderNotFound, name)
	}

	b.certificateProviders.Delete(name)
	delete(b.resourceTags, arn.Build("iot", b.region, b.accountID, fmt.Sprintf("certificateprovider/%s", name)))

	return nil
}

// RegistrationConfig holds JITP registration configuration for a CA
// certificate (types.RegistrationConfig, aws-sdk-go-v2/service/iot@v1.77.4).
type RegistrationConfig struct {
	RoleARN      string `json:"roleArn,omitempty"`
	TemplateBody string `json:"templateBody,omitempty"`
	TemplateName string `json:"templateName,omitempty"`
}

// CACertificate represents an IoT CA certificate.
type CACertificate struct {
	RegistrationConfig RegistrationConfig `json:"-"`
	CertificateARN     string             `json:"certificateArn"`
	CertificateID      string             `json:"certificateId"`
	Status             string             `json:"status"`
	CertificatePem     string             `json:"certificatePem,omitempty"`
	OwnedBy            string             `json:"ownedBy,omitempty"`
	AutoRegistration   string             `json:"autoRegistrationStatus,omitempty"`
	CreationDate       float64            `json:"creationDate,omitempty"`
	LastModifiedDate   float64            `json:"lastModifiedDate,omitempty"`
}

func cloneCACert(c *CACertificate) *CACertificate {
	cp := *c

	return &cp
}

func (b *InMemoryBackend) caCertARN(id string) string {
	return arn.Build("iot", b.region, b.accountID, fmt.Sprintf("cacert/%s", id))
}

func (b *InMemoryBackend) RegisterCACertificate(
	pem, status string,
	tags map[string]string,
	regConfig RegistrationConfig,
) (*CACertificate, error) {
	b.mu.Lock()
	defer b.mu.Unlock()

	id := uuid.NewString()[:12]
	now := float64(time.Now().Unix())
	ca := &CACertificate{
		CertificateID:      id,
		CertificateARN:     b.caCertARN(id),
		Status:             status,
		CertificatePem:     pem,
		CreationDate:       now,
		LastModifiedDate:   now,
		OwnedBy:            b.accountID,
		AutoRegistration:   "DISABLE",
		RegistrationConfig: regConfig,
	}
	if ca.Status == "" {
		ca.Status = "ACTIVE"
	}
	b.caCertificates.Put(ca)
	b.putResourceTagsLocked(ca.CertificateARN, tags)

	return cloneCACert(ca), nil
}

func (b *InMemoryBackend) DescribeCACertificate(id string) (*CACertificate, error) {
	b.mu.RLock()
	defer b.mu.RUnlock()

	ca, ok := b.caCertificates.Get(id)
	if !ok {
		return nil, fmt.Errorf("CA certificate %q not found: %w", id, ErrResourceNotFound)
	}

	return cloneCACert(ca), nil
}

func (b *InMemoryBackend) ListCACertificates() []*CACertificate {
	b.mu.RLock()
	defer b.mu.RUnlock()

	out := make([]*CACertificate, 0, b.caCertificates.Len())
	for _, v := range b.caCertificates.Snapshot() {
		out = append(out, cloneCACert(v))
	}

	return out
}

// UpdateCACertificateInput is the input for UpdateCACertificate. NewStatus
// and NewAutoRegistrationStatus are real query parameters, not body fields
// (iot@v1.77.4 serializers.go
// awsRestjson1_serializeOpHttpBindingsUpdateCACertificateInput); RegistrationConfig
// and RemoveAutoRegistration are real body fields
// (awsRestjson1_serializeOpDocumentUpdateCACertificateInput) -- all four
// were previously entirely unimplemented beyond NewStatus, which itself was
// read from the wrong location (body instead of query), so a real client's
// status change was always silently dropped.
type UpdateCACertificateInput struct {
	RegistrationConfig        *RegistrationConfig
	NewStatus                 string
	NewAutoRegistrationStatus string
	RemoveAutoRegistration    bool
}

func (b *InMemoryBackend) UpdateCACertificate(id string, input *UpdateCACertificateInput) error {
	b.mu.Lock()
	defer b.mu.Unlock()

	ca, ok := b.caCertificates.Get(id)
	if !ok {
		return fmt.Errorf("CA certificate %q not found: %w", id, ErrResourceNotFound)
	}
	if input.NewStatus != "" {
		ca.Status = input.NewStatus
	}
	if input.RemoveAutoRegistration {
		ca.AutoRegistration = ""
	} else if input.NewAutoRegistrationStatus != "" {
		ca.AutoRegistration = input.NewAutoRegistrationStatus
	}
	if input.RegistrationConfig != nil {
		ca.RegistrationConfig = *input.RegistrationConfig
	}
	ca.LastModifiedDate = float64(time.Now().Unix())

	return nil
}

func (b *InMemoryBackend) DeleteCACertificate(id string) error {
	b.mu.Lock()
	defer b.mu.Unlock()

	if !b.caCertificates.Has(id) {
		return fmt.Errorf("CA certificate %q not found: %w", id, ErrResourceNotFound)
	}
	b.caCertificates.Delete(id)
	// resourceTags[ca.CertificateARN] is intentionally left: id is
	// uuid.NewString()[:12] (RegisterCACertificate), fresh every call
	// regardless of PEM content, so no re-register can ever land on this
	// ARN again -- unlike the name-keyed resources, there's no observable
	// leak to clean up here.

	return nil
}

func (b *InMemoryBackend) ListCertificatesByCA(caID string) []*Certificate {
	b.mu.RLock()
	defer b.mu.RUnlock()

	var out []*Certificate
	for _, v := range b.certificates.Snapshot() {
		cert := v
		if cert.CACertificateID == caID {
			cp := *cert
			out = append(out, &cp)
		}
	}

	return out
}

func (b *InMemoryBackend) CancelCertificateTransfer(certID string) error {
	b.mu.Lock()
	defer b.mu.Unlock()

	cert, ok := b.certificates.Get(certID)
	if !ok {
		return fmt.Errorf("certificate %q not found: %w", certID, ErrCertificateNotFound)
	}

	if cert.Status != certStatusPendingTransfer {
		return fmt.Errorf("%w: certificate %q is not pending transfer", ErrValidation, certID)
	}

	cert.Status = certStatusInactive
	cert.LastModifiedAt = time.Now()
	cert.TransferredTo = ""
	delete(b.certificateTransfers, certID)

	return nil
}

// CreateProvisioningClaim creates a PENDING_ACTIVATION claim certificate and
// a fake key pair for fleet provisioning (iot@v1.77.4 api_op_CreateProvisioningClaim.go).
func (b *InMemoryBackend) CreateProvisioningClaim(
	templateName string,
) (*Certificate, time.Time, string, string, error) {
	b.mu.Lock()
	defer b.mu.Unlock()

	if _, ok := b.provTemplates.Get(templateName); !ok {
		return nil, time.Time{}, "", "", fmt.Errorf(
			"provisioning template %q not found: %w", templateName, ErrResourceNotFound,
		)
	}

	cert := b.newCertificate(fakePEM, certStatusPendingActivation, certModeDefault)
	b.certificates.Put(cert)
	cp := *cert

	return &cp, time.Now().Add(provisioningClaimTTL), fakePublicKey, fakePrivateKey, nil
}

// CreateKeysAndCertificate creates a new certificate with generated fake keys.
func (b *InMemoryBackend) CreateKeysAndCertificate(setAsActive bool) (*Certificate, string, string, error) {
	b.mu.Lock()
	defer b.mu.Unlock()

	status := certStatusInactive
	if setAsActive {
		status = certStatusActive
	}
	cert := b.newCertificate(fakePEM, status, certModeDefault)
	b.certificates.Put(cert)
	cp := *cert

	return &cp, fakePublicKey, fakePrivateKey, nil
}

// TransferCertificate initiates a certificate transfer to another account.
func (b *InMemoryBackend) TransferCertificate(certID, targetAccount, transferMessage string) error {
	b.mu.Lock()
	defer b.mu.Unlock()

	cert, ok := b.certificates.Get(certID)
	if !ok {
		return fmt.Errorf("certificate %q not found: %w", certID, ErrCertificateNotFound)
	}
	now := time.Now()
	cert.Status = certStatusPendingTransfer
	cert.LastModifiedAt = now
	cert.TransferDate = now
	cert.TransferredTo = targetAccount
	cert.TransferMessage = transferMessage
	b.certificateTransfers[certID] = targetAccount

	return nil
}

// RejectCertificateTransfer rejects a pending certificate transfer. Only
// valid while the certificate is PENDING_TRANSFER; matches real AWS IoT's
// InvalidRequestException for a certificate that isn't pending transfer.
func (b *InMemoryBackend) RejectCertificateTransfer(certID, rejectReason string) error {
	b.mu.Lock()
	defer b.mu.Unlock()

	cert, ok := b.certificates.Get(certID)
	if !ok {
		return fmt.Errorf("certificate %q not found: %w", certID, ErrCertificateNotFound)
	}

	if cert.Status != certStatusPendingTransfer {
		return fmt.Errorf("%w: certificate %q is not pending transfer", ErrValidation, certID)
	}

	cert.Status = certStatusInactive
	cert.LastModifiedAt = time.Now()
	cert.TransferRejectDate = time.Now()
	cert.TransferRejectReason = rejectReason
	cert.TransferredTo = ""
	delete(b.certificateTransfers, certID)

	return nil
}

const fakePublicKey = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2a2rwplBQLzHPZe5TNJG
pECOsDSZBBFKpbD+mBBpMBWMdQwCgYIKoZIzj0EAwIDSQADRgIhANXBFB+AAAAA
-----END PUBLIC KEY-----`

//nolint:gosec // fakePrivateKey is a test-only placeholder, not a real credential
const fakePrivateKey = `-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEA2a2rwplBQLzHPZe5TNJGpECOsDSZBBFKpbD+mBBpMBWMdQwC
gYIKoZIzj0EAwIDSQADRgIhANXBFB+AAAAA
-----END RSA PRIVATE KEY-----`

// OutgoingCertificate describes a certificate pending transfer to another
// AWS account.
type OutgoingCertificate struct {
	CertificateARN  string  `json:"certificateArn"`
	CertificateID   string  `json:"certificateId"`
	TransferredTo   string  `json:"transferredTo,omitempty"`
	TransferMessage string  `json:"transferMessage,omitempty"`
	CreationDate    float64 `json:"creationDate,omitempty"`
	TransferDate    float64 `json:"transferDate,omitempty"`
}

// ListOutgoingCertificates lists certificates whose status is
// PENDING_TRANSFER, derived from real, stored certificate state.
func (b *InMemoryBackend) ListOutgoingCertificates() []*OutgoingCertificate {
	b.mu.RLock()
	defer b.mu.RUnlock()

	out := make([]*OutgoingCertificate, 0)

	for _, v := range b.certificates.Snapshot() {
		cert := v
		if cert.Status != certStatusPendingTransfer {
			continue
		}

		out = append(out, &OutgoingCertificate{
			CertificateARN: cert.ARN,
			CertificateID:  cert.CertificateID,
			CreationDate:   float64(cert.CreatedAt.Unix()),
			TransferDate:   float64(cert.LastModifiedAt.Unix()),
		})
	}

	return out
}
