// Package appconfig provides an in-memory stub for the AWS AppConfig service,
// which manages feature flags and application configuration.
package appconfig

import (
	"crypto/rand"
	"encoding/binary"
	"strconv"

	"github.com/google/uuid"

	"github.com/blackbirdworks/gopherstack/pkgs/arn"
	"github.com/blackbirdworks/gopherstack/pkgs/lockmetrics"
	"github.com/blackbirdworks/gopherstack/pkgs/page"
	"github.com/blackbirdworks/gopherstack/pkgs/store"
)

const (
	contentTypeOctetStream = "application/octet-stream"

	// contentTypeHostedLocation is the well-known ConfigurationProfile
	// LocationUri value ("hosted") that marks a profile's configuration
	// as stored by AppConfig itself (hostedConfigVersions), as opposed to
	// an external source (SSM Parameter Store, S3, ...) this backend
	// cannot validate against.
	contentTypeHostedLocation = "hosted"

	// triggeredByUser is the TriggeredBy value this backend records for
	// every state transition initiated by an explicit API call (as
	// opposed to one this backend drives itself, e.g. "APPCONFIG"),
	// shared by the deployment and experiment-run event families.
	triggeredByUser = "USER"
)

const appConfigIDChars = "abcdefghijklmnopqrstuvwxyz0123456789"

// newResourceID generates a cryptographically random 7-character lowercase alphanumeric ID,
// matching the format of real AWS AppConfig resource IDs (4-7 chars required by the provider).
func newResourceID() string {
	const length = 7
	b := make([]byte, length)
	charCount := uint64(len(appConfigIDChars))

	for i := range b {
		var v [8]byte
		_, _ = rand.Read(v[:])
		b[i] = appConfigIDChars[binary.BigEndian.Uint64(v[:])%charCount]
	}

	return string(b)
}

// InMemoryBackend implements StorageBackend for AppConfig using a
// store.Registry of store.Table-backed resource collections.
//
// applications, deploymentStrategies, extensions, and extensionAssociations
// are flat, top-level collections keyed by their own real identity field
// (ID), matching the services/sesv2 / services/dax / services/datasync
// clean-direct-register template.
//
// environments and configProfiles were previously nested two levels deep
// (outer key = applicationID; inner key = the resource's own ID). Both
// Environment.ID and ConfigurationProfile.ID are generated by the same
// globally-random newResourceID() every other resource in this backend
// uses (not parent-scoped), so -- per the opsworks/datasync "globally-unique
// ID, bare-ID lookups" precedent -- each registers DIRECTLY on its own ID,
// with a companion byApp *store.Index (grouping entries by ApplicationID)
// added additively for the per-application List/cascade-delete operations
// the nested maps used to answer directly. A second byAppName *store.Index
// (composite "applicationID|name" key) replaces the old
// environmentsByName/configProfilesByName nested reverse maps for the
// per-application name-uniqueness checks.
//
// hostedConfigVersions and deployments were previously nested three levels
// deep (outer key = applicationID; middle key = profileID/environmentID;
// inner key = an int32 VersionNumber/DeploymentNumber). Unlike the resource
// IDs above, VersionNumber and DeploymentNumber are per-parent counters --
// unique only within their owning profile/environment, not globally -- so
// per the composite-key rule each flattens to one *store.Table keyed by a
// composite "applicationID|parentID|number" string (see hcvKey/deploymentKey
// below), with companion *store.Index values grouping entries by profile/env
// (List operations) and by application (DeleteApplication's cascade delete).
// hostedConfigVersions additionally carries a byLabel *store.Index replacing
// the old versionLabelIndex raw map: VersionLabel uniqueness is answered by
// the index instead of a parallel set.
//
// Left as plain maps (not store.Table-backed):
//   - tags (map[string]map[string]string): its values are plain string
//     maps, not *T, so it does not fit store.Table's keyed-by-identity-value
//     shape.
//   - versionCounters, deploymentCounters (map[string]map[string]int32):
//     their values are int32, not *T. Both must survive Snapshot/Restore
//     (see persistence.go) since they are the source of truth for the next
//     version/deployment number -- reconstructing them from the tables'
//     current contents would under-count after any delete.
//   - accountSettings is a single struct, not a map at all.
type InMemoryBackend struct {
	extensionsByName               *store.Index[Extension]
	deploymentStrategiesByName     *store.Index[DeploymentStrategy]
	applicationsByName             *store.Index[Application]
	environments                   *store.Table[Environment]
	environmentsByApp              *store.Index[Environment]
	environmentsByAppName          *store.Index[Environment]
	configProfiles                 *store.Table[ConfigurationProfile]
	configProfilesByApp            *store.Index[ConfigurationProfile]
	configProfilesByAppName        *store.Index[ConfigurationProfile]
	hostedConfigVersions           *store.Table[HostedConfigurationVersion]
	hostedConfigVersionsByProfile  *store.Index[HostedConfigurationVersion]
	hostedConfigVersionsByApp      *store.Index[HostedConfigurationVersion]
	hostedConfigVersionsByLabel    *store.Index[HostedConfigurationVersion]
	deploymentStrategies           *store.Table[DeploymentStrategy]
	extensionsByID                 *store.Index[Extension]
	deployments                    *store.Table[Deployment]
	applications                   *store.Table[Application]
	extensions                     *store.Table[Extension]
	deploymentsByApp               *store.Index[Deployment]
	registry                       *store.Registry
	deployedConfigs                map[string]string
	extensionAssociations          *store.Table[ExtensionAssociation]
	tags                           map[string]map[string]string
	versionCounters                map[string]map[string]int32
	deploymentCounters             map[string]map[string]int32
	deploymentsByEnv               *store.Index[Deployment]
	deploymentTimers               map[string]*deploymentTimer
	accountSettings                AccountSettings
	mu                             *lockmetrics.RWMutex
	experimentRunCounters          map[string]int32
	experimentRunEvents            map[string][]ExperimentRunEvent
	experimentRunsByDef            *store.Index[ExperimentRun]
	experimentRuns                 *store.Table[ExperimentRun]
	experimentDefinitions          *store.Table[ExperimentDefinition]
	experimentDefinitionsByApp     *store.Index[ExperimentDefinition]
	experimentDefinitionsByAppName *store.Index[ExperimentDefinition]
	configPublisher                DeployedConfigurationPublisher
	appConfig                      any
	region                         string
	accountID                      string
	paginationSecret               string
	deploymentReconcilerAlive      bool
}

// NewInMemoryBackend creates a new InMemoryBackend for AppConfig.
func NewInMemoryBackend(accountID, region string) *InMemoryBackend {
	b := &InMemoryBackend{
		tags:                  make(map[string]map[string]string),
		versionCounters:       make(map[string]map[string]int32),
		deploymentCounters:    make(map[string]map[string]int32),
		deployedConfigs:       make(map[string]string),
		deploymentTimers:      make(map[string]*deploymentTimer),
		experimentRunEvents:   make(map[string][]ExperimentRunEvent),
		experimentRunCounters: make(map[string]int32),
		registry:              store.NewRegistry(),
		mu:                    lockmetrics.New("appconfig"),
		paginationSecret:      uuid.NewString(),
		accountID:             accountID,
		region:                region,
	}
	registerAllTables(b)

	return b
}

// PaginationSecret returns the HMAC secret for pagination tokens.
func (b *InMemoryBackend) PaginationSecret() string { return b.paginationSecret }

// appconfigARN builds an AppConfig resource ARN for tag lookup/cleanup.
func (b *InMemoryBackend) appconfigARN(resourcePath string) string {
	return arn.Build("appconfig", b.region, b.accountID, resourcePath)
}

// ---- composite keys ----
//
// environments and configProfiles register directly on their own ID (see
// the InMemoryBackend doc comment), so appNameKey is used only to build the
// byAppName index key for per-application name-uniqueness checks.
// hostedConfigVersions and deployments register on a composite key because
// VersionNumber/DeploymentNumber are unique only within their parent.
func appNameKey(applicationID, name string) string { return applicationID + "|" + name }

func appEnvKey(applicationID, environmentID string) string {
	return applicationID + "|" + environmentID
}

func appProfileKey(applicationID, profileID string) string {
	return applicationID + "|" + profileID
}

func hcvKey(applicationID, profileID string, versionNumber int32) string {
	return appProfileKey(applicationID, profileID) + "|" + strconv.FormatInt(int64(versionNumber), 10)
}

func hcvLabelKey(applicationID, profileID, label string) string {
	return appProfileKey(applicationID, profileID) + "|" + label
}

func deploymentKey(applicationID, environmentID string, deploymentNumber int32) string {
	return appEnvKey(applicationID, environmentID) + "|" + strconv.FormatInt(int64(deploymentNumber), 10)
}

// appEnvProfileKey builds the deployedConfigs key for a given
// application/environment/configuration-profile triple.
func appEnvProfileKey(applicationID, environmentID, profileID string) string {
	return appEnvKey(applicationID, environmentID) + "|" + profileID
}

// extensionVersionKey builds the composite key extensions registers under:
// each row is one addressable (extensionID, versionNumber) pair.
func extensionVersionKey(extensionID string, versionNumber int32) string {
	return extensionID + "|" + strconv.FormatInt(int64(versionNumber), 10)
}

// experimentRunKey builds the composite key experimentRuns (and
// experimentRunEvents) register/index under: Run is a counter scoped to
// one experiment definition, not globally unique, matching the
// hcvKey/deploymentKey precedent above.
func experimentRunKey(experimentDefinitionID string, run int32) string {
	return experimentDefinitionID + "|" + strconv.FormatInt(int64(run), 10)
}

// experimentDefinitionARN builds the ARN an ExperimentDefinition's tags are
// stored under.
func (b *InMemoryBackend) experimentDefinitionARN(applicationID, experimentDefinitionID string) string {
	return b.appconfigARN("application/" + applicationID + "/experimentdefinition/" + experimentDefinitionID)
}

// experimentRunARN builds the ARN an ExperimentRun's tags are stored under.
func (b *InMemoryBackend) experimentRunARN(applicationID, experimentDefinitionID string, run int32) string {
	return b.experimentDefinitionARN(applicationID, experimentDefinitionID) +
		"/experimentrun/" + strconv.FormatInt(int64(run), 10)
}

// appConfigPaginate applies HMAC-signed token-based pagination to a sorted slice.
func appConfigPaginate[T any](all []T, nextToken, secret string, maxResults int) ([]T, string) {
	const defaultLimit = 50

	p := page.NewHMAC(all, nextToken, secret, maxResults, defaultLimit)

	return p.Data, p.Next
}
